// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qwdljgtdlqrjgypkjgih.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF3ZGxqZ3RkbHFyamd5cGtqZ2loIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcwNDMwMjMsImV4cCI6MjA3MjYxOTAyM30.BroO7DJ02MkPt0Ete2SS-tygovG8gxTg6k_yPQYPAgk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});